<?php 
// echo "<pre>";
// print_r($edit->name);
// die;
?>
<form action="/signup/update/" method="post">
    <input type="hidden" name="id" value="<?php print_r( $edit->_id.''); ?>">
<p>
<label for="name"> Name:</label>
<input type="text" name="name" value="<?php print_r($edit->name);  ?>" >
</p>
<p>
<label for="eamil">Email:</label>
<input type="email" name="email" value="<?php print_r($edit->email); ?>">
</p>
<button class="btn btn-primary" type="submit">Update</button>
</form>